export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const FETCH_METRICS = "EVENT/FETCH_METRICS";
export const METRICS_RECEIVED = "EVENT/METRICS_RECEIVED";
export const FETCH_METRICS_DATA = "EVENT/FETCH_METRICS_DATA";
export const METRICS_DATA_RECEIVED = "EVENT/METRICS_DATA_RECEIVED";
